require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'spec/dummy/**/*'
    - 'spec/tmp/**/*'
    - 'spec/isolation/abstract_unit.rb'
    - 'vendor/bundle/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

# DisabledByDefault for RSpec
RSpec:
  Enabled: false

RSpec/ContextWording:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true
