module Routes2spec
  # Routes2spec::RequestSpecFormatter class
  class RequestSpecFormatter
    STATUS: untyped

    SYMBOL_STATUS: untyped

    def initialize: (?::Hash[untyped, untyped] opts) -> void

    def result: () -> untyped

    def section_title: (untyped title) -> nil

    def section: (untyped routes) -> untyped

    def header: (untyped routes) -> nil

    def no_routes: (*untyped) -> nil
  end
end
