#!/usr/bin/env ruby

APP_PATH = File.expand_path("../config/application", __dir__)
require_relative "../config/boot"

require "routes2spec/routes2spec_command"
Routes2spec::Routes2specCommand.perform("routes2spec", ARGV, {})
