name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: test on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install bundler
        run: gem install bundler
      - name: Setup
        run: bin/setup
      - name: RSpec
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install bundler
        run: gem install bundler
      - name: Setup
        run: bin/setup
      - name: Rubocop
        run: bundle exec rubocop --fail-level W
